/**
 * @file test_client_api.c
 * @brief Client API surface and guard-path tests
 */

#include "test_utils.h"
#include "client/dc_client.h"
#include "core/dc_status.h"
#include "core/dc_log.h"

static void test_client_symbol_surface(void) {
    TEST_ASSERT((&dc_gateway_info_init) != NULL, "symbol dc_gateway_info_init");
    TEST_ASSERT((&dc_gateway_info_free) != NULL, "symbol dc_gateway_info_free");
    TEST_ASSERT((&dc_client_add_guild_member_role) != NULL, "symbol dc_client_add_guild_member_role");
    TEST_ASSERT((&dc_client_add_thread_member) != NULL, "symbol dc_client_add_thread_member");
    TEST_ASSERT((&dc_client_batch_edit_application_command_permissions_json) != NULL, "symbol dc_client_batch_edit_application_command_permissions_json");
    TEST_ASSERT((&dc_client_begin_guild_prune_json) != NULL, "symbol dc_client_begin_guild_prune_json");
    TEST_ASSERT((&dc_client_bulk_delete_messages_json) != NULL, "symbol dc_client_bulk_delete_messages_json");
    TEST_ASSERT((&dc_client_bulk_guild_ban_json) != NULL, "symbol dc_client_bulk_guild_ban_json");
    TEST_ASSERT((&dc_client_bulk_overwrite_global_application_commands_json) != NULL, "symbol dc_client_bulk_overwrite_global_application_commands_json");
    TEST_ASSERT((&dc_client_bulk_overwrite_guild_application_commands_json) != NULL, "symbol dc_client_bulk_overwrite_guild_application_commands_json");
    TEST_ASSERT((&dc_client_config_init) != NULL, "symbol dc_client_config_init");
    TEST_ASSERT((&dc_client_config_set_user_agent_info) != NULL, "symbol dc_client_config_set_user_agent_info");
    TEST_ASSERT((&dc_client_create) != NULL, "symbol dc_client_create");
    TEST_ASSERT((&dc_client_create_auto_moderation_rule_json) != NULL, "symbol dc_client_create_auto_moderation_rule_json");
    TEST_ASSERT((&dc_client_create_channel_invite_json) != NULL, "symbol dc_client_create_channel_invite_json");
    TEST_ASSERT((&dc_client_create_channel_webhook_json) != NULL, "symbol dc_client_create_channel_webhook_json");
    TEST_ASSERT((&dc_client_create_command_simple) != NULL, "symbol dc_client_create_command_simple");
    TEST_ASSERT((&dc_client_create_dm_channel) != NULL, "symbol dc_client_create_dm_channel");
    TEST_ASSERT((&dc_client_create_dm_channel_json) != NULL, "symbol dc_client_create_dm_channel_json");
    TEST_ASSERT((&dc_client_create_global_application_command_json) != NULL, "symbol dc_client_create_global_application_command_json");
    TEST_ASSERT((&dc_client_create_guild_application_command_json) != NULL, "symbol dc_client_create_guild_application_command_json");
    TEST_ASSERT((&dc_client_create_guild_ban) != NULL, "symbol dc_client_create_guild_ban");
    TEST_ASSERT((&dc_client_create_guild_channel_json) != NULL, "symbol dc_client_create_guild_channel_json");
    TEST_ASSERT((&dc_client_create_guild_emoji_json) != NULL, "symbol dc_client_create_guild_emoji_json");
    TEST_ASSERT((&dc_client_create_guild_role_json) != NULL, "symbol dc_client_create_guild_role_json");
    TEST_ASSERT((&dc_client_create_guild_scheduled_event_json) != NULL, "symbol dc_client_create_guild_scheduled_event_json");
    TEST_ASSERT((&dc_client_create_guild_soundboard_sound_json) != NULL, "symbol dc_client_create_guild_soundboard_sound_json");
    TEST_ASSERT((&dc_client_create_guild_sticker_multipart) != NULL, "symbol dc_client_create_guild_sticker_multipart");
    TEST_ASSERT((&dc_client_create_message) != NULL, "symbol dc_client_create_message");
    TEST_ASSERT((&dc_client_create_message_command_simple) != NULL, "symbol dc_client_create_message_command_simple");
    TEST_ASSERT((&dc_client_create_message_json) != NULL, "symbol dc_client_create_message_json");
    TEST_ASSERT((&dc_client_create_reaction_encoded) != NULL, "symbol dc_client_create_reaction_encoded");
    TEST_ASSERT((&dc_client_create_stage_instance_json) != NULL, "symbol dc_client_create_stage_instance_json");
    TEST_ASSERT((&dc_client_create_user_command_simple) != NULL, "symbol dc_client_create_user_command_simple");
    TEST_ASSERT((&dc_client_crosspost_message_json) != NULL, "symbol dc_client_crosspost_message_json");
    TEST_ASSERT((&dc_client_delete_all_reactions) != NULL, "symbol dc_client_delete_all_reactions");
    TEST_ASSERT((&dc_client_delete_all_reactions_for_emoji_encoded) != NULL, "symbol dc_client_delete_all_reactions_for_emoji_encoded");
    TEST_ASSERT((&dc_client_delete_auto_moderation_rule) != NULL, "symbol dc_client_delete_auto_moderation_rule");
    TEST_ASSERT((&dc_client_delete_channel) != NULL, "symbol dc_client_delete_channel");
    TEST_ASSERT((&dc_client_delete_channel_permission) != NULL, "symbol dc_client_delete_channel_permission");
    TEST_ASSERT((&dc_client_delete_global_application_command) != NULL, "symbol dc_client_delete_global_application_command");
    TEST_ASSERT((&dc_client_delete_guild_application_command) != NULL, "symbol dc_client_delete_guild_application_command");
    TEST_ASSERT((&dc_client_delete_guild_emoji) != NULL, "symbol dc_client_delete_guild_emoji");
    TEST_ASSERT((&dc_client_delete_guild_integration) != NULL, "symbol dc_client_delete_guild_integration");
    TEST_ASSERT((&dc_client_delete_guild_role) != NULL, "symbol dc_client_delete_guild_role");
    TEST_ASSERT((&dc_client_delete_guild_scheduled_event) != NULL, "symbol dc_client_delete_guild_scheduled_event");
    TEST_ASSERT((&dc_client_delete_guild_soundboard_sound) != NULL, "symbol dc_client_delete_guild_soundboard_sound");
    TEST_ASSERT((&dc_client_delete_guild_sticker) != NULL, "symbol dc_client_delete_guild_sticker");
    TEST_ASSERT((&dc_client_delete_invite_json) != NULL, "symbol dc_client_delete_invite_json");
    TEST_ASSERT((&dc_client_delete_message) != NULL, "symbol dc_client_delete_message");
    TEST_ASSERT((&dc_client_delete_own_reaction_encoded) != NULL, "symbol dc_client_delete_own_reaction_encoded");
    TEST_ASSERT((&dc_client_delete_stage_instance) != NULL, "symbol dc_client_delete_stage_instance");
    TEST_ASSERT((&dc_client_delete_user_reaction_encoded) != NULL, "symbol dc_client_delete_user_reaction_encoded");
    TEST_ASSERT((&dc_client_delete_webhook) != NULL, "symbol dc_client_delete_webhook");
    TEST_ASSERT((&dc_client_delete_webhook_message) != NULL, "symbol dc_client_delete_webhook_message");
    TEST_ASSERT((&dc_client_delete_webhook_with_token) != NULL, "symbol dc_client_delete_webhook_with_token");
    TEST_ASSERT((&dc_client_edit_application_command_permissions_json) != NULL, "symbol dc_client_edit_application_command_permissions_json");
    TEST_ASSERT((&dc_client_edit_channel_permissions_json) != NULL, "symbol dc_client_edit_channel_permissions_json");
    TEST_ASSERT((&dc_client_edit_message_content) != NULL, "symbol dc_client_edit_message_content");
    TEST_ASSERT((&dc_client_edit_message_json) != NULL, "symbol dc_client_edit_message_json");
    TEST_ASSERT((&dc_client_edit_webhook_message_json) != NULL, "symbol dc_client_edit_webhook_message_json");
    TEST_ASSERT((&dc_client_end_poll_json) != NULL, "symbol dc_client_end_poll_json");
    TEST_ASSERT((&dc_client_execute_webhook_json) != NULL, "symbol dc_client_execute_webhook_json");
    TEST_ASSERT((&dc_client_follow_announcement_channel_json) != NULL, "symbol dc_client_follow_announcement_channel_json");
    TEST_ASSERT((&dc_client_free) != NULL, "symbol dc_client_free");
    TEST_ASSERT((&dc_client_get_application_command_permissions_json) != NULL, "symbol dc_client_get_application_command_permissions_json");
    TEST_ASSERT((&dc_client_get_application_role_connection_metadata_json) != NULL, "symbol dc_client_get_application_role_connection_metadata_json");
    TEST_ASSERT((&dc_client_get_auto_moderation_rule_json) != NULL, "symbol dc_client_get_auto_moderation_rule_json");
    TEST_ASSERT((&dc_client_get_channel) != NULL, "symbol dc_client_get_channel");
    TEST_ASSERT((&dc_client_get_channel_invites_json) != NULL, "symbol dc_client_get_channel_invites_json");
    TEST_ASSERT((&dc_client_get_channel_pins_json) != NULL, "symbol dc_client_get_channel_pins_json");
    TEST_ASSERT((&dc_client_get_channel_webhooks_json) != NULL, "symbol dc_client_get_channel_webhooks_json");
    TEST_ASSERT((&dc_client_get_current_application_json) != NULL, "symbol dc_client_get_current_application_json");
    TEST_ASSERT((&dc_client_get_current_user) != NULL, "symbol dc_client_get_current_user");
    TEST_ASSERT((&dc_client_get_current_user_application_role_connection_json) != NULL, "symbol dc_client_get_current_user_application_role_connection_json");
    TEST_ASSERT((&dc_client_get_current_user_connections_json) != NULL, "symbol dc_client_get_current_user_connections_json");
    TEST_ASSERT((&dc_client_get_current_user_guild_member) != NULL, "symbol dc_client_get_current_user_guild_member");
    TEST_ASSERT((&dc_client_get_current_user_guild_member_json) != NULL, "symbol dc_client_get_current_user_guild_member_json");
    TEST_ASSERT((&dc_client_get_current_user_guilds_json) != NULL, "symbol dc_client_get_current_user_guilds_json");
    TEST_ASSERT((&dc_client_get_current_user_voice_state_json) != NULL, "symbol dc_client_get_current_user_voice_state_json");
    TEST_ASSERT((&dc_client_get_gateway_info) != NULL, "symbol dc_client_get_gateway_info");
    TEST_ASSERT((&dc_client_get_global_application_command_json) != NULL, "symbol dc_client_get_global_application_command_json");
    TEST_ASSERT((&dc_client_get_global_application_commands_json) != NULL, "symbol dc_client_get_global_application_commands_json");
    TEST_ASSERT((&dc_client_get_guild) != NULL, "symbol dc_client_get_guild");
    TEST_ASSERT((&dc_client_get_guild_application_command_json) != NULL, "symbol dc_client_get_guild_application_command_json");
    TEST_ASSERT((&dc_client_get_guild_application_command_permissions_json) != NULL, "symbol dc_client_get_guild_application_command_permissions_json");
    TEST_ASSERT((&dc_client_get_guild_application_commands_json) != NULL, "symbol dc_client_get_guild_application_commands_json");
    TEST_ASSERT((&dc_client_get_guild_audit_log_json) != NULL, "symbol dc_client_get_guild_audit_log_json");
    TEST_ASSERT((&dc_client_get_guild_ban_json) != NULL, "symbol dc_client_get_guild_ban_json");
    TEST_ASSERT((&dc_client_get_guild_bans_json) != NULL, "symbol dc_client_get_guild_bans_json");
    TEST_ASSERT((&dc_client_get_guild_channels) != NULL, "symbol dc_client_get_guild_channels");
    TEST_ASSERT((&dc_client_get_guild_channels_json) != NULL, "symbol dc_client_get_guild_channels_json");
    TEST_ASSERT((&dc_client_get_guild_emoji_json) != NULL, "symbol dc_client_get_guild_emoji_json");
    TEST_ASSERT((&dc_client_get_guild_integrations_json) != NULL, "symbol dc_client_get_guild_integrations_json");
    TEST_ASSERT((&dc_client_get_guild_invites_json) != NULL, "symbol dc_client_get_guild_invites_json");
    TEST_ASSERT((&dc_client_get_guild_json) != NULL, "symbol dc_client_get_guild_json");
    TEST_ASSERT((&dc_client_get_guild_member) != NULL, "symbol dc_client_get_guild_member");
    TEST_ASSERT((&dc_client_get_guild_member_json) != NULL, "symbol dc_client_get_guild_member_json");
    TEST_ASSERT((&dc_client_get_guild_onboarding_json) != NULL, "symbol dc_client_get_guild_onboarding_json");
    TEST_ASSERT((&dc_client_get_guild_preview_json) != NULL, "symbol dc_client_get_guild_preview_json");
    TEST_ASSERT((&dc_client_get_guild_prune_count_json) != NULL, "symbol dc_client_get_guild_prune_count_json");
    TEST_ASSERT((&dc_client_get_guild_role_json) != NULL, "symbol dc_client_get_guild_role_json");
    TEST_ASSERT((&dc_client_get_guild_role_member_counts_json) != NULL, "symbol dc_client_get_guild_role_member_counts_json");
    TEST_ASSERT((&dc_client_get_guild_roles) != NULL, "symbol dc_client_get_guild_roles");
    TEST_ASSERT((&dc_client_get_guild_roles_json) != NULL, "symbol dc_client_get_guild_roles_json");
    TEST_ASSERT((&dc_client_get_guild_scheduled_event_json) != NULL, "symbol dc_client_get_guild_scheduled_event_json");
    TEST_ASSERT((&dc_client_get_guild_scheduled_event_users_json) != NULL, "symbol dc_client_get_guild_scheduled_event_users_json");
    TEST_ASSERT((&dc_client_get_guild_soundboard_sound_json) != NULL, "symbol dc_client_get_guild_soundboard_sound_json");
    TEST_ASSERT((&dc_client_get_guild_sticker_json) != NULL, "symbol dc_client_get_guild_sticker_json");
    TEST_ASSERT((&dc_client_get_guild_vanity_url_json) != NULL, "symbol dc_client_get_guild_vanity_url_json");
    TEST_ASSERT((&dc_client_get_guild_voice_regions_json) != NULL, "symbol dc_client_get_guild_voice_regions_json");
    TEST_ASSERT((&dc_client_get_guild_webhooks_json) != NULL, "symbol dc_client_get_guild_webhooks_json");
    TEST_ASSERT((&dc_client_get_guild_welcome_screen_json) != NULL, "symbol dc_client_get_guild_welcome_screen_json");
    TEST_ASSERT((&dc_client_get_guild_widget_json) != NULL, "symbol dc_client_get_guild_widget_json");
    TEST_ASSERT((&dc_client_get_guild_widget_settings_json) != NULL, "symbol dc_client_get_guild_widget_settings_json");
    TEST_ASSERT((&dc_client_get_invite_json) != NULL, "symbol dc_client_get_invite_json");
    TEST_ASSERT((&dc_client_get_message) != NULL, "symbol dc_client_get_message");
    TEST_ASSERT((&dc_client_get_pinned_messages_json) != NULL, "symbol dc_client_get_pinned_messages_json");
    TEST_ASSERT((&dc_client_get_poll_answer_voters_json) != NULL, "symbol dc_client_get_poll_answer_voters_json");
    TEST_ASSERT((&dc_client_get_reactions_encoded_json) != NULL, "symbol dc_client_get_reactions_encoded_json");
    TEST_ASSERT((&dc_client_get_stage_instance_json) != NULL, "symbol dc_client_get_stage_instance_json");
    TEST_ASSERT((&dc_client_get_sticker_json) != NULL, "symbol dc_client_get_sticker_json");
    TEST_ASSERT((&dc_client_get_sticker_pack_json) != NULL, "symbol dc_client_get_sticker_pack_json");
    TEST_ASSERT((&dc_client_get_thread_member_json) != NULL, "symbol dc_client_get_thread_member_json");
    TEST_ASSERT((&dc_client_get_user) != NULL, "symbol dc_client_get_user");
    TEST_ASSERT((&dc_client_get_user_voice_state_json) != NULL, "symbol dc_client_get_user_voice_state_json");
    TEST_ASSERT((&dc_client_get_webhook_json) != NULL, "symbol dc_client_get_webhook_json");
    TEST_ASSERT((&dc_client_get_webhook_message_json) != NULL, "symbol dc_client_get_webhook_message_json");
    TEST_ASSERT((&dc_client_get_webhook_with_token_json) != NULL, "symbol dc_client_get_webhook_with_token_json");
    TEST_ASSERT((&dc_client_init) != NULL, "symbol dc_client_init");
    TEST_ASSERT((&dc_client_interaction_callback_json) != NULL, "symbol dc_client_interaction_callback_json");
    TEST_ASSERT((&dc_client_interaction_create_followup_message) != NULL, "symbol dc_client_interaction_create_followup_message");
    TEST_ASSERT((&dc_client_interaction_create_followup_message_json) != NULL, "symbol dc_client_interaction_create_followup_message_json");
    TEST_ASSERT((&dc_client_interaction_defer_message) != NULL, "symbol dc_client_interaction_defer_message");
    TEST_ASSERT((&dc_client_interaction_defer_update) != NULL, "symbol dc_client_interaction_defer_update");
    TEST_ASSERT((&dc_client_interaction_delete_followup_message) != NULL, "symbol dc_client_interaction_delete_followup_message");
    TEST_ASSERT((&dc_client_interaction_delete_original_response) != NULL, "symbol dc_client_interaction_delete_original_response");
    TEST_ASSERT((&dc_client_interaction_edit_followup_message) != NULL, "symbol dc_client_interaction_edit_followup_message");
    TEST_ASSERT((&dc_client_interaction_edit_followup_message_json) != NULL, "symbol dc_client_interaction_edit_followup_message_json");
    TEST_ASSERT((&dc_client_interaction_edit_original_response) != NULL, "symbol dc_client_interaction_edit_original_response");
    TEST_ASSERT((&dc_client_interaction_edit_original_response_json) != NULL, "symbol dc_client_interaction_edit_original_response_json");
    TEST_ASSERT((&dc_client_interaction_respond_message) != NULL, "symbol dc_client_interaction_respond_message");
    TEST_ASSERT((&dc_client_interaction_respond_message_json) != NULL, "symbol dc_client_interaction_respond_message_json");
    TEST_ASSERT((&dc_client_interaction_show_modal_json) != NULL, "symbol dc_client_interaction_show_modal_json");
    TEST_ASSERT((&dc_client_interaction_update_message_json) != NULL, "symbol dc_client_interaction_update_message_json");
    TEST_ASSERT((&dc_client_join_thread) != NULL, "symbol dc_client_join_thread");
    TEST_ASSERT((&dc_client_leave_guild) != NULL, "symbol dc_client_leave_guild");
    TEST_ASSERT((&dc_client_leave_thread) != NULL, "symbol dc_client_leave_thread");
    TEST_ASSERT((&dc_client_list_active_guild_threads_json) != NULL, "symbol dc_client_list_active_guild_threads_json");
    TEST_ASSERT((&dc_client_list_auto_moderation_rules_json) != NULL, "symbol dc_client_list_auto_moderation_rules_json");
    TEST_ASSERT((&dc_client_list_channel_messages_json) != NULL, "symbol dc_client_list_channel_messages_json");
    TEST_ASSERT((&dc_client_list_default_soundboard_sounds_json) != NULL, "symbol dc_client_list_default_soundboard_sounds_json");
    TEST_ASSERT((&dc_client_list_guild_emojis_json) != NULL, "symbol dc_client_list_guild_emojis_json");
    TEST_ASSERT((&dc_client_list_guild_members) != NULL, "symbol dc_client_list_guild_members");
    TEST_ASSERT((&dc_client_list_guild_members_json) != NULL, "symbol dc_client_list_guild_members_json");
    TEST_ASSERT((&dc_client_list_guild_scheduled_events_json) != NULL, "symbol dc_client_list_guild_scheduled_events_json");
    TEST_ASSERT((&dc_client_list_guild_soundboard_sounds_json) != NULL, "symbol dc_client_list_guild_soundboard_sounds_json");
    TEST_ASSERT((&dc_client_list_guild_stickers_json) != NULL, "symbol dc_client_list_guild_stickers_json");
    TEST_ASSERT((&dc_client_list_joined_private_archived_threads_json) != NULL, "symbol dc_client_list_joined_private_archived_threads_json");
    TEST_ASSERT((&dc_client_list_private_archived_threads_json) != NULL, "symbol dc_client_list_private_archived_threads_json");
    TEST_ASSERT((&dc_client_list_public_archived_threads_json) != NULL, "symbol dc_client_list_public_archived_threads_json");
    TEST_ASSERT((&dc_client_list_sticker_packs_json) != NULL, "symbol dc_client_list_sticker_packs_json");
    TEST_ASSERT((&dc_client_list_thread_members_json) != NULL, "symbol dc_client_list_thread_members_json");
    TEST_ASSERT((&dc_client_list_voice_regions_json) != NULL, "symbol dc_client_list_voice_regions_json");
    TEST_ASSERT((&dc_client_modify_auto_moderation_rule_json) != NULL, "symbol dc_client_modify_auto_moderation_rule_json");
    TEST_ASSERT((&dc_client_modify_channel_json) != NULL, "symbol dc_client_modify_channel_json");
    TEST_ASSERT((&dc_client_modify_current_application_json) != NULL, "symbol dc_client_modify_current_application_json");
    TEST_ASSERT((&dc_client_modify_current_member_json) != NULL, "symbol dc_client_modify_current_member_json");
    TEST_ASSERT((&dc_client_modify_current_user_json) != NULL, "symbol dc_client_modify_current_user_json");
    TEST_ASSERT((&dc_client_modify_current_user_nick_json) != NULL, "symbol dc_client_modify_current_user_nick_json");
    TEST_ASSERT((&dc_client_modify_current_user_voice_state_json) != NULL, "symbol dc_client_modify_current_user_voice_state_json");
    TEST_ASSERT((&dc_client_modify_global_application_command_json) != NULL, "symbol dc_client_modify_global_application_command_json");
    TEST_ASSERT((&dc_client_modify_guild) != NULL, "symbol dc_client_modify_guild");
    TEST_ASSERT((&dc_client_modify_guild_application_command_json) != NULL, "symbol dc_client_modify_guild_application_command_json");
    TEST_ASSERT((&dc_client_modify_guild_channel_positions_json) != NULL, "symbol dc_client_modify_guild_channel_positions_json");
    TEST_ASSERT((&dc_client_modify_guild_emoji_json) != NULL, "symbol dc_client_modify_guild_emoji_json");
    TEST_ASSERT((&dc_client_modify_guild_incident_actions_json) != NULL, "symbol dc_client_modify_guild_incident_actions_json");
    TEST_ASSERT((&dc_client_modify_guild_json) != NULL, "symbol dc_client_modify_guild_json");
    TEST_ASSERT((&dc_client_modify_guild_member_json) != NULL, "symbol dc_client_modify_guild_member_json");
    TEST_ASSERT((&dc_client_modify_guild_onboarding_json) != NULL, "symbol dc_client_modify_guild_onboarding_json");
    TEST_ASSERT((&dc_client_modify_guild_role_json) != NULL, "symbol dc_client_modify_guild_role_json");
    TEST_ASSERT((&dc_client_modify_guild_role_positions_json) != NULL, "symbol dc_client_modify_guild_role_positions_json");
    TEST_ASSERT((&dc_client_modify_guild_scheduled_event_json) != NULL, "symbol dc_client_modify_guild_scheduled_event_json");
    TEST_ASSERT((&dc_client_modify_guild_soundboard_sound_json) != NULL, "symbol dc_client_modify_guild_soundboard_sound_json");
    TEST_ASSERT((&dc_client_modify_guild_sticker_json) != NULL, "symbol dc_client_modify_guild_sticker_json");
    TEST_ASSERT((&dc_client_modify_guild_welcome_screen_json) != NULL, "symbol dc_client_modify_guild_welcome_screen_json");
    TEST_ASSERT((&dc_client_modify_guild_widget_json) != NULL, "symbol dc_client_modify_guild_widget_json");
    TEST_ASSERT((&dc_client_modify_stage_instance_json) != NULL, "symbol dc_client_modify_stage_instance_json");
    TEST_ASSERT((&dc_client_modify_user_voice_state_json) != NULL, "symbol dc_client_modify_user_voice_state_json");
    TEST_ASSERT((&dc_client_modify_webhook_json) != NULL, "symbol dc_client_modify_webhook_json");
    TEST_ASSERT((&dc_client_modify_webhook_with_token_json) != NULL, "symbol dc_client_modify_webhook_with_token_json");
    TEST_ASSERT((&dc_client_pin_message) != NULL, "symbol dc_client_pin_message");
    TEST_ASSERT((&dc_client_process) != NULL, "symbol dc_client_process");
    TEST_ASSERT((&dc_client_remove_guild_ban) != NULL, "symbol dc_client_remove_guild_ban");
    TEST_ASSERT((&dc_client_remove_guild_member) != NULL, "symbol dc_client_remove_guild_member");
    TEST_ASSERT((&dc_client_remove_guild_member_role) != NULL, "symbol dc_client_remove_guild_member_role");
    TEST_ASSERT((&dc_client_remove_thread_member) != NULL, "symbol dc_client_remove_thread_member");
    TEST_ASSERT((&dc_client_request_guild_members) != NULL, "symbol dc_client_request_guild_members");
    TEST_ASSERT((&dc_client_request_soundboard_sounds) != NULL, "symbol dc_client_request_soundboard_sounds");
    TEST_ASSERT((&dc_client_search_guild_members_json) != NULL, "symbol dc_client_search_guild_members_json");
    TEST_ASSERT((&dc_client_send_soundboard_sound_json) != NULL, "symbol dc_client_send_soundboard_sound_json");
    TEST_ASSERT((&dc_client_set_logger) != NULL, "symbol dc_client_set_logger");
    TEST_ASSERT((&dc_client_shutdown) != NULL, "symbol dc_client_shutdown");
    TEST_ASSERT((&dc_client_start) != NULL, "symbol dc_client_start");
    TEST_ASSERT((&dc_client_start_forum_or_media_thread_json) != NULL, "symbol dc_client_start_forum_or_media_thread_json");
    TEST_ASSERT((&dc_client_start_thread_from_message_json) != NULL, "symbol dc_client_start_thread_from_message_json");
    TEST_ASSERT((&dc_client_start_thread_without_message_json) != NULL, "symbol dc_client_start_thread_without_message_json");
    TEST_ASSERT((&dc_client_start_with_gateway_url) != NULL, "symbol dc_client_start_with_gateway_url");
    TEST_ASSERT((&dc_client_stop) != NULL, "symbol dc_client_stop");
    TEST_ASSERT((&dc_client_trigger_typing_indicator) != NULL, "symbol dc_client_trigger_typing_indicator");
    TEST_ASSERT((&dc_client_unpin_message) != NULL, "symbol dc_client_unpin_message");
    TEST_ASSERT((&dc_client_update_application_role_connection_metadata_json) != NULL, "symbol dc_client_update_application_role_connection_metadata_json");
    TEST_ASSERT((&dc_client_update_current_user_application_role_connection_json) != NULL, "symbol dc_client_update_current_user_application_role_connection_json");
    TEST_ASSERT((&dc_client_update_presence) != NULL, "symbol dc_client_update_presence");
    TEST_ASSERT((&dc_client_update_voice_state) != NULL, "symbol dc_client_update_voice_state");
}

static void test_client_config_and_lifecycle(void) {
    dc_gateway_info_t info;
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_gateway_info_init(NULL), "gateway_info_init null");
    TEST_ASSERT_EQ(DC_OK, dc_gateway_info_init(&info), "gateway_info_init ok");
    TEST_ASSERT_EQ(0u, dc_string_length(&info.url), "gateway_info_init empty url");
    dc_gateway_info_free(&info);

    dc_client_config_t cfg;
    dc_client_config_init(&cfg);
    TEST_ASSERT_EQ(DC_HTTP_AUTH_BOT, cfg.auth_type, "config default auth bot");
    TEST_ASSERT_EQ((uint32_t)30000, cfg.http_timeout_ms, "config default http timeout");
    TEST_ASSERT_EQ((uint32_t)60000, cfg.gateway_timeout_ms, "config default gw timeout");
    TEST_ASSERT_EQ(DC_LOG_INFO, cfg.log_level, "config default log level");

    dc_user_agent_t ua = {
        .name = "fishydslib",
        .version = "0.0.0",
        .url = "https://example.com",
        .extra = "TestBot/0.1.0"
    };
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_config_set_user_agent_info(NULL, &ua),
                   "set user-agent null config");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_config_set_user_agent_info(&cfg, NULL),
                   "set user-agent null ua");
    TEST_ASSERT_EQ(DC_OK, dc_client_config_set_user_agent_info(&cfg, &ua),
                   "set user-agent info ok");
    TEST_ASSERT_EQ(1, cfg.use_user_agent_info, "set user-agent info enabled");

    dc_client_t* client = NULL;
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create(NULL, &client), "client_create null cfg");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create(&cfg, NULL), "client_create null out");

    cfg.token = "";
    TEST_ASSERT_EQ(DC_ERROR_INVALID_PARAM, dc_client_create(&cfg, &client),
                   "client_create empty token");

    dc_client_config_init(&cfg);
    cfg.token = "test_token";
    TEST_ASSERT_EQ(DC_OK, dc_client_create(&cfg, &client), "client_create ok");
    TEST_ASSERT_NOT_NULL(client, "client_create output non-null");
    TEST_ASSERT_EQ(DC_ERROR_INVALID_PARAM, dc_client_start_with_gateway_url(client, "ws://invalid"),
                   "start_with_gateway_url rejects non-wss");
    {
        dc_status_t process_st = dc_client_process(client, 0);
        TEST_ASSERT(process_st == DC_OK || process_st == DC_ERROR_TIMEOUT || process_st == DC_ERROR_INVALID_STATE,
                    "process before connect accepted status");
    }
    TEST_ASSERT_EQ(DC_OK, dc_client_stop(client), "stop disconnected client ok");
    dc_client_shutdown(client);

    client = NULL;
    TEST_ASSERT_EQ(DC_OK, dc_client_init(&cfg, &client), "client_init alias ok");
    TEST_ASSERT_NOT_NULL(client, "client_init output non-null");
    dc_client_free(client);
}

static void test_client_null_guard_coverage(void) {
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_start(NULL), "dc_client_start null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_start_with_gateway_url(NULL, NULL), "dc_client_start_with_gateway_url null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_stop(NULL), "dc_client_stop null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_process(NULL, (uint32_t)0), "dc_client_process null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_gateway_info(NULL, NULL), "dc_client_get_gateway_info null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user(NULL, NULL), "dc_client_get_current_user null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_user(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_user null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_current_user_json(NULL, NULL, NULL), "dc_client_modify_current_user_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_guilds_json(NULL, (uint32_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, 0, NULL), "dc_client_get_current_user_guilds_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_guild_member_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_current_user_guild_member_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_guild_member(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_current_user_guild_member null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_leave_guild(NULL, (dc_snowflake_t)0), "dc_client_leave_guild null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_dm_channel_json(NULL, NULL, NULL), "dc_client_create_dm_channel_json null client");
    TEST_ASSERT_EQ(DC_ERROR_INVALID_PARAM, dc_client_create_dm_channel(NULL, (dc_snowflake_t)0, NULL), "dc_client_create_dm_channel validates recipient before client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_connections_json(NULL, NULL), "dc_client_get_current_user_connections_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_application_role_connection_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_current_user_application_role_connection_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_update_current_user_application_role_connection_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_update_current_user_application_role_connection_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_message(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_message_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_channels_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_channels_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_channels(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_channels null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_channel(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_channel null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_channel_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_channel_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_channel(NULL, (dc_snowflake_t)0, NULL), "dc_client_delete_channel null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_channel_messages_json(NULL, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_list_channel_messages_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_message(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_edit_message_content(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_edit_message_content null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_message(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_pin_message(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_pin_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_unpin_message(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_unpin_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_pinned_messages_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_pinned_messages_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_channel_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_channel_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_member_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_member_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_member(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_member null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_members_json(NULL, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, NULL), "dc_client_list_guild_members_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_members(NULL, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, NULL), "dc_client_list_guild_members null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_roles_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_roles_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_roles(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_roles null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_role_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_role_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_role_positions_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_role_positions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_role_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_role_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_role(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_role null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_remove_guild_member(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_remove_guild_member null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_add_guild_member_role(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_add_guild_member_role null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_remove_guild_member_role(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_remove_guild_member_role null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_channel_webhook_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_channel_webhook_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_channel_webhooks_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_channel_webhooks_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_webhooks_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_webhooks_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_webhook_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_webhook_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_webhook_with_token_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_get_webhook_with_token_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_webhook_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_webhook_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_webhook_with_token_json(NULL, (dc_snowflake_t)0, NULL, NULL, NULL), "dc_client_modify_webhook_with_token_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_webhook(NULL, (dc_snowflake_t)0), "dc_client_delete_webhook null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_webhook_with_token(NULL, (dc_snowflake_t)0, NULL), "dc_client_delete_webhook_with_token null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_execute_webhook_json(NULL, (dc_snowflake_t)0, NULL, NULL, 0, NULL), "dc_client_execute_webhook_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_webhook_message_json(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_webhook_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_edit_webhook_message_json(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, NULL), "dc_client_edit_webhook_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_webhook_message(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_webhook_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_application_json(NULL, NULL), "dc_client_get_current_application_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_current_application_json(NULL, NULL, NULL), "dc_client_modify_current_application_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_application_role_connection_metadata_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_application_role_connection_metadata_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_update_application_role_connection_metadata_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_update_application_role_connection_metadata_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_global_application_commands_json(NULL, (dc_snowflake_t)0, 0, NULL), "dc_client_get_global_application_commands_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_global_application_command_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_global_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_global_application_command_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_global_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_global_application_command_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_global_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_global_application_command(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_global_application_command null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_bulk_overwrite_global_application_commands_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_bulk_overwrite_global_application_commands_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_application_commands_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, 0, NULL), "dc_client_get_guild_application_commands_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_application_command_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_application_command_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_application_command_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_application_command_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_application_command(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_application_command null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_bulk_overwrite_guild_application_commands_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_bulk_overwrite_guild_application_commands_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_application_command_permissions_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_application_command_permissions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_application_command_permissions_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_application_command_permissions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_edit_application_command_permissions_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_edit_application_command_permissions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_batch_edit_application_command_permissions_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_batch_edit_application_command_permissions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_crosspost_message_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_crosspost_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_edit_message_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_edit_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_bulk_delete_messages_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_bulk_delete_messages_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_reaction_encoded(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_create_reaction_encoded null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_own_reaction_encoded(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_delete_own_reaction_encoded null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_user_reaction_encoded(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0), "dc_client_delete_user_reaction_encoded null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_reactions_encoded_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, 0, (dc_snowflake_t)0, (uint32_t)0, NULL), "dc_client_get_reactions_encoded_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_all_reactions(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_all_reactions null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_all_reactions_for_emoji_encoded(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_delete_all_reactions_for_emoji_encoded null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_channel_pins_json(NULL, (dc_snowflake_t)0, NULL, (uint32_t)0, NULL), "dc_client_get_channel_pins_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_edit_channel_permissions_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_edit_channel_permissions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_channel_permission(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_channel_permission null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_channel_invites_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_channel_invites_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_channel_invite_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_channel_invite_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_invite_json(NULL, NULL, 0, 0, (dc_snowflake_t)0, NULL), "dc_client_get_invite_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_invite_json(NULL, NULL, NULL), "dc_client_delete_invite_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_follow_announcement_channel_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_follow_announcement_channel_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_trigger_typing_indicator(NULL, (dc_snowflake_t)0), "dc_client_trigger_typing_indicator null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_start_thread_from_message_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_start_thread_from_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_start_thread_without_message_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_start_thread_without_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_start_forum_or_media_thread_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_start_forum_or_media_thread_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_join_thread(NULL, (dc_snowflake_t)0), "dc_client_join_thread null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_add_thread_member(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_add_thread_member null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_leave_thread(NULL, (dc_snowflake_t)0), "dc_client_leave_thread null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_remove_thread_member(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_remove_thread_member null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_thread_member_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, 0, NULL), "dc_client_get_thread_member_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_thread_members_json(NULL, (dc_snowflake_t)0, 0, (dc_snowflake_t)0, (uint32_t)0, NULL), "dc_client_list_thread_members_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_public_archived_threads_json(NULL, (dc_snowflake_t)0, NULL, (uint32_t)0, NULL), "dc_client_list_public_archived_threads_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_private_archived_threads_json(NULL, (dc_snowflake_t)0, NULL, (uint32_t)0, NULL), "dc_client_list_private_archived_threads_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_joined_private_archived_threads_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (uint32_t)0, NULL), "dc_client_list_joined_private_archived_threads_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_preview_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_preview_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_channel_positions_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_modify_guild_channel_positions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_active_guild_threads_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_list_active_guild_threads_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_search_guild_members_json(NULL, (dc_snowflake_t)0, NULL, (uint32_t)0, NULL), "dc_client_search_guild_members_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_member_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_member_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_current_member_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_current_member_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_current_user_nick_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_current_user_nick_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_bans_json(NULL, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_bans_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_ban_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_ban_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_ban(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, 0), "dc_client_create_guild_ban null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_remove_guild_ban(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_remove_guild_ban null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_bulk_guild_ban_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_bulk_guild_ban_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_role_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_role_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_role_member_counts_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_role_member_counts_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_prune_count_json(NULL, (dc_snowflake_t)0, (uint32_t)0, NULL, NULL), "dc_client_get_guild_prune_count_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_begin_guild_prune_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_begin_guild_prune_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_voice_regions_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_voice_regions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_invites_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_invites_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_integrations_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_integrations_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_integration(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_integration null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_audit_log_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, (dc_snowflake_t)0, (uint32_t)0, NULL), "dc_client_get_guild_audit_log_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_widget_settings_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_widget_settings_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_widget_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_widget_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_widget_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_widget_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_vanity_url_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_vanity_url_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_welcome_screen_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_welcome_screen_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_welcome_screen_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_welcome_screen_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_onboarding_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_guild_onboarding_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_onboarding_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_onboarding_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_incident_actions_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_incident_actions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_auto_moderation_rules_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_list_auto_moderation_rules_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_auto_moderation_rule_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_auto_moderation_rule_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_auto_moderation_rule_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_auto_moderation_rule_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_auto_moderation_rule_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_auto_moderation_rule_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_auto_moderation_rule(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_auto_moderation_rule null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_stage_instance_json(NULL, NULL, NULL), "dc_client_create_stage_instance_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_stage_instance_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_stage_instance_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_stage_instance_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_stage_instance_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_stage_instance(NULL, (dc_snowflake_t)0), "dc_client_delete_stage_instance null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_poll_answer_voters_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (uint32_t)0, (dc_snowflake_t)0, (uint32_t)0, NULL), "dc_client_get_poll_answer_voters_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_end_poll_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_end_poll_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_send_soundboard_sound_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_send_soundboard_sound_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_default_soundboard_sounds_json(NULL, NULL), "dc_client_list_default_soundboard_sounds_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_soundboard_sounds_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_list_guild_soundboard_sounds_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_soundboard_sound_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_soundboard_sound_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_soundboard_sound_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_soundboard_sound_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_soundboard_sound_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_soundboard_sound_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_soundboard_sound(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_soundboard_sound null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_voice_regions_json(NULL, NULL), "dc_client_list_voice_regions_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_current_user_voice_state_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_current_user_voice_state_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_user_voice_state_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_user_voice_state_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_current_user_voice_state_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_modify_current_user_voice_state_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_user_voice_state_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_modify_user_voice_state_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_scheduled_events_json(NULL, (dc_snowflake_t)0, 0, NULL), "dc_client_list_guild_scheduled_events_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_scheduled_event_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_scheduled_event_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_scheduled_event_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, 0, NULL), "dc_client_get_guild_scheduled_event_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_scheduled_event_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_scheduled_event_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_scheduled_event(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_scheduled_event null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_scheduled_event_users_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, (uint32_t)0, 0, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_scheduled_event_users_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_emojis_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_list_guild_emojis_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_emoji_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_emoji_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_emoji_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_create_guild_emoji_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_emoji_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_emoji_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_emoji(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_emoji null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_sticker_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_sticker_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_sticker_packs_json(NULL, NULL), "dc_client_list_sticker_packs_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_sticker_pack_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_get_sticker_pack_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_list_guild_stickers_json(NULL, (dc_snowflake_t)0, NULL), "dc_client_list_guild_stickers_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_get_guild_sticker_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_get_guild_sticker_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_guild_sticker_multipart(NULL, (dc_snowflake_t)0, NULL, NULL, NULL, NULL, (size_t)0, NULL, NULL, NULL), "dc_client_create_guild_sticker_multipart null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_modify_guild_sticker_json(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL), "dc_client_modify_guild_sticker_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_delete_guild_sticker(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0), "dc_client_delete_guild_sticker null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_update_presence(NULL, NULL, NULL, 0), "dc_client_update_presence null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_command_simple(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL, NULL, NULL, NULL, 0), "dc_client_create_command_simple null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_user_command_simple(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_create_user_command_simple null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_create_message_command_simple(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, NULL), "dc_client_create_message_command_simple null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_callback_json(NULL, (dc_snowflake_t)0, NULL, (dc_interaction_callback_type_t)0, NULL), "dc_client_interaction_callback_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_respond_message_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_interaction_respond_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_defer_message(NULL, (dc_snowflake_t)0, NULL, 0), "dc_client_interaction_defer_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_defer_update(NULL, (dc_snowflake_t)0, NULL), "dc_client_interaction_defer_update null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_update_message_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_interaction_update_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_show_modal_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_interaction_show_modal_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_respond_message(NULL, (dc_snowflake_t)0, NULL, NULL, 0), "dc_client_interaction_respond_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_edit_original_response_json(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_interaction_edit_original_response_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_edit_original_response(NULL, (dc_snowflake_t)0, NULL, NULL), "dc_client_interaction_edit_original_response null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_delete_original_response(NULL, (dc_snowflake_t)0, NULL), "dc_client_interaction_delete_original_response null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_create_followup_message_json(NULL, (dc_snowflake_t)0, NULL, NULL, NULL), "dc_client_interaction_create_followup_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_create_followup_message(NULL, (dc_snowflake_t)0, NULL, NULL, 0, NULL), "dc_client_interaction_create_followup_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_edit_followup_message_json(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, NULL), "dc_client_interaction_edit_followup_message_json null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_edit_followup_message(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0, NULL), "dc_client_interaction_edit_followup_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_interaction_delete_followup_message(NULL, (dc_snowflake_t)0, NULL, (dc_snowflake_t)0), "dc_client_interaction_delete_followup_message null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_request_guild_members(NULL, (dc_snowflake_t)0, NULL, (uint32_t)0, 0, NULL, (size_t)0, NULL), "dc_client_request_guild_members null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_request_soundboard_sounds(NULL, NULL, (size_t)0), "dc_client_request_soundboard_sounds null client");
    TEST_ASSERT_EQ(DC_ERROR_NULL_POINTER, dc_client_update_voice_state(NULL, (dc_snowflake_t)0, (dc_snowflake_t)0, 0, 0), "dc_client_update_voice_state null client");
}

int main(void) {
    TEST_SUITE_BEGIN("Client API Tests");
    test_client_symbol_surface();
    test_client_config_and_lifecycle();
    test_client_null_guard_coverage();
    TEST_SUITE_END("Client API Tests");
}
